### ISSUE TITLE
Using ES6 Promise.all() with Mongoose

### ISSUE THREAD

**Issue by chrisveness** [aheckmann/mpromise#13]
I'm not sure if this is an mpromise question or a Mongoose question, but is there any way to use (or to shim) the forthcoming ES6/Harmony Promise.all() method with Mongoose?

**Comment by pravin-d** [comment]
Yes.. Cases where we need to generate charts, etc from various models involves a bunch of parallel calls, whose results needs to be crunched by a series of functions.
:+1:

**Comment by lbeschastny** [comment]
@chrisveness are you proposing to add static `.all` method to `mpromise`, or are you asking about using an existing `Promise.all()` implementation with `mpromise` promises?

I think that any existing `Promise.all()` implementation should work with `mpromise`. And if it's not true, then something is definitely broken.

**Comment by chrisveness** [comment]
In the time since I asked the original question, I've decided the future for me lies with Koa rather than Express, using native generators and ‘yield’ – code is enormously simpler using yield than either callbacks or promises, and performance doesn’t seem an issue. Using Koa you can make parallel calls by [yielding to an array of functions](https://github.com/tj/co#arrays). For current planned projects I’ll be using SQL databases, but issue [#1859](https://github.com/LearnBoost/mongoose/issues/1859) deals with using Mongoose with Koa. I'm just hoping that either Node.js reaches v0.12 or io.js gets to stable before I get to production stage...
